{% set name = "ale-py" %}
{% set version = "0.7.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mgbellemare/Arcade-Learning-Environment/archive/refs/tags/v{{ version }}.tar.gz  # If getting the source from GitHub, remove the line above,
  sha256: b2b9c33292ea3386af61371d94ab0c5d07c61010754f0dc4447f0b14b71303e9

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
  run:
    - numpy
    - python

test:
  imports:
    #- ale_py
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/mgbellemare/Arcade-Learning-Environment
  license: GPL-2.0-only
  license_family: GPL
  license_file: LICENSE.md
  summary: 'The Arcade Learning Environment (ALE) is a simple framework that allows 
    researchers and hobbyists to develop AI agents for Atari 2600 games.'
  doc_url: https://github.com/mgbellemare/Arcade-Learning-Environment
  dev_url: https://github.com/mgbellemare/Arcade-Learning-Environment

extra:
  recipe-maintainers:
    - test
