{% set name = "mariadb-connector-c" %}
{% set version = "3.1.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mariadb-corporation/mariadb-connector-c/archive/v{{ version }}.tar.gz
  sha256: 2615f0824c467097818e54809516f249ced4152f2536cded152227f883222a8e

build:
  number: 0
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja # [win]
    - make # [not win]
  host:
    - openssl # [not win]

about:
  home: https://github.com/simplejson/simplejson
  license: LGPL-2.1
  license_family: LGPL
  license_file: COPYING.LIB
  summary: 'This is LGPL MariaDB client library that can be used to connect to MySQL
    or MariaDB.'
  description: |
    This is LGPL MariaDB client library that can be used to connect to MySQL
    or MariaDB. This code is based on the LGPL libmysql client library from MySQL 3.23
    and PHP's mysqlnd extension.
  dev_url: https://github.com/mariadb-corporation/mariadb-connector-c

extra:
  recipe-maintainers:
    - mxr-conda
    - d-cunningham
